export const audiobookLabels = {
  en: {
    title: 'The Noble Audiobooks',
    intro: 'Choose a book. Put on your headphones. Continue the journey in words.',
    start: 'Start listening', continue: 'Continue listening', pause: 'Pause', playChapter: 'Play selected chapter',
    open: 'Open audiobook', back: 'All audiobooks', chapters: 'chapters',
    language: 'Audio language', english: 'English', urdu: 'Urdu',
    narrator: 'Cedar · AI narration', position: 'Your listening position',
    chapterList: 'Chapters', duration: 'Total duration', now: 'Current chapter', selected: 'Selected chapter',
    notice: 'Source-linked editorial audiobooks—not hadith quotations, full translations or historical voice recordings.',
    script: 'Read this chapter', evidence: 'Sources and context', readSource: 'Read source',
    visual: 'Open Story view', back15: 'Back 15 seconds', forward15: 'Forward 15 seconds',
    readExplore: 'Read & explore', homeListen: 'Listen as an audiobook',
    offline: 'Saved MP3s, generated once. Listening makes no AI requests. Background playback depends on your browser and device.',
  },
  ur: {
    title: 'نوبل آڈیو بکس',
    intro: 'کتاب منتخب کریں، ہیڈفون لگائیں اور الفاظ کے ساتھ سفر جاری رکھیے۔',
    start: 'سننا شروع کریں', continue: 'سماعت جاری رکھیں', pause: 'روکیں', playChapter: 'منتخب باب سنیں',
    open: 'آڈیو بک کھولیں', back: 'تمام آڈیو بکس', chapters: 'ابواب',
    language: 'آڈیو کی زبان', english: 'انگریزی', urdu: 'اردو',
    narrator: 'سیڈر · مصنوعی آواز', position: 'آپ کی سماعت کا مقام',
    chapterList: 'ابواب', duration: 'کل دورانیہ', now: 'موجودہ باب', selected: 'منتخب باب',
    notice: 'یہ مآخذ سے جڑی ادارتی آڈیو بکس ہیں؛ حدیث کے اقتباسات، مکمل تراجم یا تاریخی آوازوں کی ریکارڈنگ نہیں۔',
    script: 'اس باب کا متن پڑھیں', evidence: 'مآخذ اور سیاق', readSource: 'ماخذ پڑھیں',
    visual: 'بیانیہ منظر کھولیں', back15: 'پندرہ سیکنڈ پیچھے', forward15: 'پندرہ سیکنڈ آگے',
    readExplore: 'پڑھیے اور مطالعہ کیجیے', homeListen: 'آڈیو بک کی صورت میں سنیے',
    offline: 'محفوظ MP3 آڈیو، جو ایک بار تیار ہوئی ہے۔ سننے پر مصنوعی ذہانت کو نئی درخواست نہیں جاتی۔ پس منظر میں سماعت براؤزر اور آلے پر منحصر ہے۔',
  },
} as const
