import { expect, test } from '@playwright/test'

test('English reading, Arabic source, keyboard dialog and focus restoration', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('./?lang=en&view=collection&scoutTheme=light')
  await expect(page.getByRole('heading', { name: 'Explore the collection', exact: true })).toBeVisible()
  const read = page.getByRole('button', { name: /^Read: / }).first()
  await read.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('Grading & attribution', { exact: true })).toBeVisible()
  await expect(dialog.locator('.reader-arabic [lang="ar"]')).toHaveAttribute('dir', 'rtl')
  await dialog.getByText('Read the full Arabic report', { exact: true }).click()
  await expect(dialog.locator('[data-full-arabic]')).toBeVisible()
  expect((await dialog.locator('[data-full-arabic]').textContent())?.length).toBeGreaterThan(100)
  await expect(dialog.getByRole('link', { name: 'Read the full source', exact: true })).toHaveAttribute('href', /^https:\/\/sunnah\.com\//)
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(read).toBeFocused()
  expect(errors).toEqual([])
})

test('cross-language search, source filters, cautions and empty-state recovery', async ({ page }) => {
  await page.goto('./?lang=en&view=collection')
  const search = page.getByRole('searchbox', { name: 'Search the narrations', exact: true })
  await search.fill('۳۵۵۲')
  await expect(page.locator('.narration-card')).not.toHaveCount(0)
  await expect(page.locator('.narration-card').first()).toContainText('Moon')
  await search.fill('not-a-real-result-837465')
  await expect(page.getByRole('heading', { name: 'No narrations found', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters', exact: true }).last().click()
  await page.getByRole('combobox', { name: 'Narration grading', exact: true }).selectOption('weak')
  await expect(page.locator('.narration-card').first()).toContainText('Read with caution')
  await page.getByRole('button', { name: /^Read: / }).first().click()
  await expect(page.getByRole('dialog').getByText('Its details should not be presented as established descriptions.', { exact: false })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Collection', exact: true }).selectOption('bukhari')
  await expect(page.getByRole('heading', { name: 'No narrations found', exact: true })).toBeVisible()
})

test('Urdu RTL, locally saved preferences and bilingual reading', async ({ page }) => {
  await page.goto('./?lang=en&view=collection&scoutTheme=light')
  await page.getByRole('button', { name: 'اردو', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ur')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await expect(page.getByRole('heading', { name: 'مجموعے کا مطالعہ', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'تاریک تھیم اختیار کریں', exact: true }).click()
  await page.getByRole('button', { name: /^محفوظ کریں:/ }).first().click()
  await page.getByRole('link', { name: /^محفوظ \(/ }).click()
  await expect(page.locator('.narration-card')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('lang', 'ur')
  await expect(page.locator('.narration-card')).toHaveCount(1)
  await page.goto('./?view=saved&grade=all')
  await expect(page.locator('html')).toHaveAttribute('lang', 'ur')
  await expect(page.locator('.narration-card')).toHaveCount(1)
  await page.getByRole('button', { name: /^پڑھیے:/ }).first().click()
  await page.getByRole('button', { name: 'دونوں زبانوں میں پڑھیں', exact: true }).click()
  await expect(page.getByRole('dialog').locator('.meaning-section[lang="ur"]')).toBeVisible()
  await expect(page.getByRole('dialog').locator('.meaning-section[lang="en"]')).toBeVisible()
  await page.getByRole('combobox', { name: 'مطالعے کے متن کا سائز', exact: true }).selectOption('larger')
  await expect(page.getByRole('dialog')).toHaveAttribute('data-text-size', 'larger')
  const overflows = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(overflows).toBe(false)
})

test('shareable narration links, reload and browser back', async ({ page }) => {
  await page.goto('./?lang=ur&grade=all#narration/face-like-the-moon-not-a-sword')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await page.reload()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'مطالعہ بند کریں', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goBack()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.goto('./?lang=en#narration/nonexistent-narration')
  await expect(page.getByRole('heading', { name: 'This narration could not be found', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to the collection', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('sources and methodology are reachable in both languages and research data downloads', async ({ page }) => {
  await page.goto('./?lang=en&view=sources')
  await expect(page.getByRole('heading', { name: 'Every description has a source.', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What “comprehensive” does not mean here', exact: true })).toBeVisible()
  await page.locator('.source-index summary').first().click()
  await expect(page.locator('.source-index details[open] a').first()).toHaveAttribute('href', /^https:\/\/sunnah\.com\//)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'JSON', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('noble-appearance-research.json')
  const stream = await download.createReadStream()
  if (!stream) throw new Error('No research download stream')
  const chunks: Buffer[] = []
  for await (const chunk of stream) chunks.push(Buffer.from(chunk))
  const data = JSON.parse(Buffer.concat(chunks).toString('utf8'))
  expect(data.entries.length).toBeGreaterThanOrEqual(60)
  expect(data.entries.some((row: { grade: { level: string } }) => row.grade.level === 'weak')).toBe(true)
  await page.getByRole('link', { name: 'Reading guide', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Read with love. Read with context.', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'اردو', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('محبت سے پڑھیے')
})

test('unavailable local storage has an honest visible warning', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Blocked', 'SecurityError') } })
  })
  await page.goto('./?lang=en&view=collection')
  await expect(page.getByRole('alert')).toContainText('cannot save your reading preferences')
  await page.getByRole('button', { name: /^Save: / }).first().click()
  await expect(page.getByRole('alert')).toContainText('cannot save')
  await page.getByRole('link', { name: /^Saved \(/ }).click()
  await expect(page.locator('.narration-card')).toHaveCount(1)
})

test('no page overflow at small widths, with loaded local fonts and no depiction images', async ({ page }) => {
  for (const language of ['en', 'ur']) {
    await page.setViewportSize({ width: 360, height: 800 })
    await page.goto(`./?lang=${language}`)
    await page.evaluate(() => document.fonts.ready)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(await page.locator('img').count()).toBe(0)
    expect(await page.evaluate(() => document.fonts.check('16px "Noto Naskh Arabic"'))).toBe(true)
    if (language === 'ur') expect(await page.evaluate(() => document.fonts.check('16px "Noto Nastaliq Urdu"'))).toBe(true)
  }
})

test('pagination, topic selection, reader navigation and browser focus stay coherent', async ({ page }) => {
  await page.goto('./?lang=en&view=collection')
  await expect(page.locator('.narration-card')).toHaveCount(12)
  await page.getByRole('button', { name: 'Load more entries', exact: true }).click()
  await expect(page.locator('.narration-card')).toHaveCount(24)
  await page.getByRole('button', { name: /^Hair \d+$/ }).click()
  await expect(page.locator('.results-heading h3')).toHaveText('Hair')
  await page.getByRole('button', { name: /^Read: / }).first().click()
  const dialog = page.getByRole('dialog')
  const firstTitle = await dialog.getByRole('heading', { level: 2 }).textContent()
  await dialog.getByRole('button', { name: 'Next entry', exact: true }).click()
  await expect(dialog.getByRole('heading', { level: 2 })).not.toHaveText(firstTitle ?? '')
  await expect(dialog.getByRole('heading', { level: 2 })).toBeFocused()
  await dialog.getByRole('button', { name: 'Previous entry', exact: true }).click()
  await expect(dialog.getByRole('heading', { level: 2 })).toHaveText(firstTitle ?? '')
  await page.keyboard.press('Tab')
  expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
})

test('clipboard denial provides a selectable link and an explicit error', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText: () => Promise.reject(new DOMException('Denied', 'NotAllowedError')) },
    })
  })
  await page.goto('./?lang=en#narration/face-like-the-moon-not-a-sword')
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Copy link', exact: true }).click()
  await expect(dialog.getByText('The browser could not copy the link. Select and copy it below.', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('textbox', { name: 'Link to this narration' })).toHaveValue(/#narration\/face-like-the-moon-not-a-sword$/)
})

test('weak bookmarks stay accessible in saved view and can be removed', async ({ page }) => {
  await page.goto('./?lang=en&grade=weak')
  await page.getByRole('button', { name: /^Save: / }).first().click()
  await page.getByRole('link', { name: /^Saved \(/ }).click()
  await expect(page.locator('.narration-card')).toHaveCount(1)
  await expect(page.locator('.narration-card')).toContainText('Read with caution')
  await page.getByRole('button', { name: /^Remove from saved: / }).click()
  await expect(page.getByRole('heading', { name: 'A place for what stays with you', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.narration-card')).toHaveCount(0)
})

test('the offline edition embeds scripts, styles, data and reading fonts', async ({ page }) => {
  const errors: string[] = []
  const requests: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => requests.push(request.url()))
  await page.goto('./noble-appearance.html?lang=ur&view=journey&shelf=appearance')
  await page.evaluate(() => document.fonts.ready)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('الفاظ میں محفوظ')
  await expect(page.locator('.journey-chapter')).toHaveCount(16)
  await expect(page.locator('.narration-card')).toHaveCount(0)
  expect(await page.evaluate(() => document.fonts.check('16px "Noto Nastaliq Urdu"'))).toBe(true)
  expect(await page.evaluate(() => document.fonts.check('16px "Noto Naskh Arabic"'))).toBe(true)
  expect(requests.every((url) => url.startsWith('data:') || new URL(url).pathname.endsWith('/noble-appearance.html'))).toBe(true)
  expect(errors).toEqual([])
  await page.context().setOffline(true)
  await page.getByRole('button', { name: 'رنگت: روایات دیکھیے', exact: true }).click()
  await expect(page.locator('.narration-card').first()).toBeVisible()
  await page.getByRole('button', { name: /^پڑھیے:/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.context().setOffline(false)
})
