import { expect, test } from './fixtures.ts'
import { audiobook, audiobookTime } from '../../src/lib/audiobooks.ts'

test('home offers a distinct audiobook entrance with three real bilingual books', async ({ page }) => {
  await page.goto('./?lang=en')
  await expect(page.getByRole('button', { name: 'Read & explore', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Listen as an audiobook', exact: true }).click()
  await expect(page).toHaveURL(/view=audiobooks/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('The Noble Audiobooks')
  await expect(page.locator('.audiobook-card')).toHaveCount(3)
  await expect(page.locator('.audiobook-cover')).toHaveCount(3)
  await page.getByRole('combobox', { name: 'Audio language', exact: true }).selectOption('ur')
  await expect(page.locator('.audiobook-card[data-book="life"] .book-facts')).toContainText(audiobookTime(audiobook('life', 'ur').duration))
  expect(await page.locator('audio').evaluate((element) => element.paused)).toBe(true)
})

test('book playback has chapter durations, fifteen-second controls and a persistent Continue action', async ({ page }) => {
  const book = audiobook('life', 'en')
  await page.goto('./?view=audiobooks&lang=en')
  const audio = page.locator('audio')
  await audio.evaluate((element) => { element.muted = true })
  await page.locator('.audiobook-card[data-book="life"]').getByRole('button', { name: 'Start listening', exact: true }).click()
  await expect(page).toHaveURL(/view=listen/)
  await expect(page.locator('.book-chapter')).toHaveCount(12)
  await expect.poll(() => audio.evaluate((element) => element.duration)).toBeGreaterThan(20)
  await audio.evaluate((element) => { element.currentTime = 20 })
  await page.getByRole('button', { name: 'Back 15 seconds', exact: true }).click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeLessThan(7)
  await page.getByRole('button', { name: 'Forward 15 seconds', exact: true }).click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(18)
  const target = book.chapters[2].episode.id
  await page.locator(`.book-chapter[data-entry="${target}"]`).click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(.2)
  await audio.evaluate((element) => { element.currentTime = 4 })
  await page.locator('.narrated-player').getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('link', { name: 'Audiobooks', exact: true }).click()
  const card = page.locator('.audiobook-card[data-book="life"]')
  await expect(card.getByRole('button', { name: 'Continue listening', exact: true })).toBeVisible()
  await page.reload()
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  await audio.evaluate((element) => { element.muted = true })
  await card.getByRole('button', { name: 'Continue listening', exact: true }).click()
  await expect(page.locator(`.book-chapter[data-entry="${target}"]`)).toHaveAttribute('aria-current', 'step')
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThanOrEqual(3.5)
  await expect(audio).toHaveCount(1)
})

test('Urdu audiobook covers and book details remain readable without starting audio', async ({ page }) => {
  await page.goto('./?view=audiobooks&lang=ur&scoutTheme=dark')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.audiobook-card[data-book="life"] .audiobook-open').click()
  await expect(page.locator('.book-detail-header h1')).toContainText('سیرت')
  await expect(page.locator('.book-chapter')).toHaveCount(12)
  expect(await page.locator('audio').evaluate((element) => element.paused)).toBe(true)
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
