import { expect, test } from '@playwright/test'

test('opening dedication honors Allah, the Prophet and both parents, then permits reading', async ({ page }) => {
  await page.goto('./?lang=en')
  const dialog = page.getByRole('dialog', { name: 'Dedication', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toHaveAccessibleDescription(/All praise belongs to Allah.*Prophet Muhammad \(PBUH\).*Farkhanda Abid.*Abid Mahmood Abid/s)
  await expect(dialog.getByRole('button', { name: 'Close dedication', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Continue to the project', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
  await page.getByRole('link', { name: 'Reading guide', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Close dedication', exact: true }).click()
  await expect(dialog).not.toBeVisible()
})

test('Urdu dedication fits a small screen and can be dismissed without local storage', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Blocked', 'SecurityError') } })
  })
  await page.setViewportSize({ width: 360, height: 640 })
  await page.goto('./?lang=ur&scoutTheme=dark')
  const dialog = page.getByRole('dialog', { name: 'انتساب', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toHaveAttribute('dir', 'rtl')
  await expect(dialog).toHaveAttribute('lang', 'ur')
  await expect(dialog).toContainText('اللہ')
  await expect(dialog).toContainText('حضرت محمد ﷺ')
  await expect(dialog).toContainText('Farkhanda Abid')
  await expect(dialog).toContainText('Abid Mahmood Abid')
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'منصوبے کا مطالعہ کریں', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
})

test('Escape dismisses the dedication without losing a shared narration', async ({ page }) => {
  await page.goto('./?lang=en#narration/face-like-the-moon-not-a-sword')
  await expect(page.getByRole('dialog', { name: 'Dedication', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await page.keyboard.press('Escape')
  const reader = page.getByRole('dialog')
  await expect(reader.getByText('Grading & attribution', { exact: true })).toBeVisible()
  await expect(reader.getByRole('heading', { level: 2 })).toBeFocused()
  await expect(page).toHaveURL(/#narration\/face-like-the-moon-not-a-sword$/)
  await page.keyboard.press('Escape')
  await expect(reader).not.toBeVisible()
})
