import { expect, test } from '@playwright/test'

test('the landing journey shows all themes and highlights, but no hadith cards until clicked', async ({ page }) => {
  await page.goto('./?lang=en')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Known through words.')
  await expect(page.locator('.journey-chapter')).toHaveCount(16)
  await expect(page.locator('.narration-card')).toHaveCount(0)
  expect(await page.locator('.journey-chapter').evaluateAll((sections) => sections.slice(0, 2).map((section) => section.getAttribute('data-topic')))).toEqual(['complexion', 'eyes'])
  expect(new Set(await page.locator('.topic-artwork').evaluateAll((items) => items.map((item) => item.getAttribute('data-motif')))).size).toBe(16)
  await page.getByRole('button', { name: 'Begin with complexion', exact: true }).click()
  await expect(page.locator('#chapter-complexion')).toBeFocused()
  const complexion = page.locator('.journey-chapter[data-topic="complexion"]')
  await expect(complexion.locator('.chapter-highlights li')).toHaveCount(2)
  await expect(complexion.getByRole('button', { name: 'View narrations about Complexion', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await complexion.getByRole('button', { name: 'View narrations about Complexion', exact: true }).click()
  await expect(complexion.locator('.narration-card').first()).toBeVisible()
  await expect(page.locator('.journey-chapter[data-topic="eyes"] .narration-card')).toHaveCount(0)
  await expect(complexion.locator('.grade-caution')).toHaveCount(0)
})

test('a highlight reference opens its own evidence only on activation', async ({ page }) => {
  await page.goto('./?lang=en')
  const citation = page.locator('.journey-chapter[data-topic="complexion"] .highlight-source').first()
  await citation.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('link', { name: 'Read the full source', exact: true })).toHaveAttribute('href', 'https://sunnah.com/bukhari:3547')
  await expect(page.locator('.narration-card')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(citation).toBeFocused()
})

test('chapters expand independently and shared narrations have unique accessible heading IDs', async ({ page }) => {
  await page.goto('./?lang=en')
  await page.getByRole('button', { name: 'View narrations about Hands & touch', exact: true }).click()
  await page.getByRole('button', { name: 'View narrations about Fragrance & perspiration', exact: true }).click()
  await expect(page.locator('[data-entry="palm-softer-than-silk-scent"]')).toHaveCount(2)
  const ids = await page.locator('[id]').evaluateAll((elements) => elements.map((element) => element.id))
  expect(new Set(ids).size).toBe(ids.length)
  const hands = page.locator('.journey-chapter[data-topic="hands"]')
  await hands.locator('.chapter-reports-footer').getByRole('button', { name: 'Hide narrations', exact: true }).click()
  await expect(hands.locator('.narration-card')).toHaveCount(0)
  await expect(hands.getByRole('button', { name: 'View narrations about Hands & touch', exact: true })).toBeFocused()
  await expect(page.locator('.journey-chapter[data-topic="fragrance"]')).toHaveAttribute('data-expanded', 'true')
})

test('cautioned reports stay opt-in and remain cautioned in the thematic reader', async ({ page }) => {
  await page.goto('./?lang=en')
  const eyes = page.locator('.journey-chapter[data-topic="eyes"]')
  await eyes.getByRole('button', { name: 'View narrations about Eyes', exact: true }).click()
  await expect(eyes.locator('.grade-caution')).toHaveCount(0)
  await eyes.getByRole('button', { name: 'Include cautioned reports', exact: true }).click()
  await expect(eyes.locator('.grade-caution').first()).toBeVisible()
  const weak = eyes.locator('.narration-card').filter({ has: page.locator('.grade-caution') }).first()
  await weak.getByRole('button', { name: /^Read: / }).click()
  await expect(page.getByRole('dialog').getByText('Read with caution', { exact: true })).toBeVisible()
  expect(new URL(page.url()).searchParams.get('view')).toBe('journey')
  expect(new URL(page.url()).searchParams.get('topic')).toBe('eyes')
  expect(new URL(page.url()).searchParams.get('grade')).toBe('all')
  await page.reload()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.journey-chapter')).toHaveCount(16)
  await expect(page.locator('.collection-results')).toHaveCount(0)
})

test('Urdu chapter navigation and language switching preserve explicit disclosure', async ({ page }) => {
  await page.goto('./?lang=ur')
  await page.getByRole('button', { name: 'رنگت سے آغاز کریں', exact: true }).click()
  const complexion = page.locator('.journey-chapter[data-topic="complexion"]')
  await complexion.getByRole('button', { name: 'اگلا موضوع: آنکھیں', exact: true }).click()
  await expect(page.locator('#chapter-eyes')).toBeFocused()
  await page.getByRole('button', { name: 'آنکھیں: روایات دیکھیے', exact: true }).click()
  await expect(page.locator('.journey-chapter[data-topic="eyes"]')).toHaveAttribute('data-expanded', 'true')
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Hide narrations about Eyes', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.journey-chapter[data-topic="complexion"]')).toHaveAttribute('data-expanded', 'false')
})

test('chapter motion stops when reading, offscreen, paused or system-reduced', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('./?lang=en')
  const complexion = page.locator('.journey-chapter[data-topic="complexion"]')
  const art = complexion.locator('.topic-artwork')
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
  await complexion.getByRole('button', { name: 'View narrations about Complexion', exact: true }).click()
  await expect(art).toHaveAttribute('data-running', 'false')
  await complexion.getByRole('button', { name: 'Hide narrations about Complexion', exact: true }).click()
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
  await complexion.getByRole('button', { name: 'Pause motion — Complexion', exact: true }).click()
  await expect(art).toHaveAttribute('data-running', 'false')
  await expect(art.locator('.topic-motion').first()).toHaveCSS('animation-name', 'none')
  await complexion.getByRole('button', { name: 'Resume motion — Complexion', exact: true }).click()
  await page.locator('.journey-chapter[data-topic="hair"] .topic-artwork').scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'false')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.topic-artwork[data-running="true"]')).toHaveCount(0)
})

test('the full searchable collection remains one explicit navigation away', async ({ page }) => {
  await page.goto('./?lang=en')
  await page.getByRole('link', { name: 'Collection', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'Search the narrations', exact: true })).toBeVisible()
  await expect(page.locator('.narration-card')).toHaveCount(12)
  expect(new URL(page.url()).searchParams.get('view')).toBe('collection')
  await page.getByRole('link', { name: 'Journey', exact: true }).click()
  await expect(page.locator('.narration-card')).toHaveCount(0)
  await expect(page.locator('.journey-chapter')).toHaveCount(16)
})
