import { expect, test } from '@playwright/test'

test('chapter listening follows without stealing focus, advances, resumes and keeps read marks explicit', async ({ page }) => {
  await page.goto('./?view=story&shelf=appearance&lang=en')
  const audio = page.locator('audio')
  await expect(audio).toHaveCount(1)
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  await audio.evaluate((element) => { element.muted = true })
  await page.locator('.story-chapter[data-topic="complexion"] .story-listen-action').click()
  const player = page.locator('.listening-player')
  await expect(player).toBeVisible()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(.2)
  await player.getByRole('checkbox', { name: 'Follow the story', exact: true }).check()
  await expect(player.getByRole('checkbox', { name: 'Follow the story', exact: true })).toBeFocused()
  await expect(page).toHaveURL(/topic=complexion/)
  const firstSource = await audio.getAttribute('src')
  await audio.evaluate((element) => { element.currentTime = element.duration - .12 })
  await expect.poll(() => audio.getAttribute('src')).not.toBe(firstSource)
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(.2)
  await page.mouse.move(10, 200)
  await page.mouse.wheel(0, 100)
  await expect(player).toContainText('Following suspended')
  await expect.poll(() => audio.evaluate((element) => element.duration)).toBeGreaterThan(4)
  await audio.evaluate((element) => { element.currentTime = 3.4 })
  await player.getByRole('button', { name: 'Pause', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('noble-project.listening.v1')!))
  const cursor = saved.positions.find((item: { entryId: string; language: string }) => item.entryId === saved.queue.currentEntryId && item.language === saved.language)
  expect(cursor.time).toBeGreaterThanOrEqual(3.3)
  await page.reload()
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  await expect(player.getByRole('checkbox', { name: 'Follow the story', exact: true })).not.toBeChecked()
  await audio.evaluate((element) => { element.muted = true })
  await player.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThanOrEqual(cursor.time - .5)
  await player.getByRole('combobox', { name: 'Narration language', exact: true }).selectOption('ur')
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  const reading = await page.evaluate(() => JSON.parse(localStorage.getItem('noble-project.reading.v1') ?? '{"entries":{}}'))
  expect(Object.values<{ read?: boolean }>(reading.entries).some((entry) => entry.read === true)).toBe(false)
})

test('the app exports a version-2 private backup and restores listening through the confirmation flow', async ({ page }) => {
  await page.goto('./?view=reading&lang=en')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download private backup', exact: true }).click()
  const download = await pending
  const stream = await download.createReadStream()
  if (!stream) throw new Error('Private backup download missing')
  const chunks: Buffer[] = []
  for await (const chunk of stream) chunks.push(Buffer.from(chunk))
  const text = Buffer.concat(chunks).toString('utf8')
  const backup = JSON.parse(text)
  expect(backup.version).toBe(2)
  expect(backup.listening.version).toBe(1)
  await page.getByLabel('Or paste private backup JSON', { exact: true }).fill(text)
  await page.getByRole('button', { name: 'Preview restore', exact: true }).click()
  const preview = page.getByRole('dialog', { name: 'Review before restoring', exact: true })
  await expect(preview).toContainText('Listening positions')
  await preview.getByRole('radio', { name: /^Replace/ }).check()
  await preview.getByRole('button', { name: 'Confirm restore', exact: true }).click()
  await expect(page.getByText('The selected private backup was restored in this browser.', { exact: true })).toBeVisible()
  expect(await page.locator('audio').evaluate((element) => element.paused)).toBe(true)
})
