import { expect, test } from '@playwright/test'

test('ornamental motion pauses on demand, persists and leaves the calligraphy still', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('./?lang=en&view=journey&shelf=appearance')
  const art = page.locator('.manuscript-art')
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
  await expect(art.locator('.rosette-rim')).toHaveCSS('animation-play-state', 'running')
  await expect(art.locator('.name-calligraphy')).toHaveCSS('animation-name', 'none')
  await expect(art.locator('.name-calligraphy')).toHaveCSS('transform', 'none')
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await expect(art).toHaveAttribute('data-running', 'false')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'paused')
  await expect(art.locator('.rosette-rim')).toHaveCSS('animation-name', 'none')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Resume motion', exact: true }).click()
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
})

test('offscreen, hidden-tab and reader states stop ambient animation', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('./?lang=en&view=journey&shelf=appearance')
  const art = page.locator('.manuscript-art')
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, get: () => true })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(art).toHaveAttribute('data-running', 'false')
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, get: () => false })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(art).toHaveAttribute('data-running', 'true')
  await page.locator('#chapter-complexion').evaluate((element) => element.scrollIntoView({ block: 'start', behavior: 'instant' }))
  await expect(art).toHaveAttribute('data-running', 'false')
  await page.getByRole('button', { name: 'View narrations about Complexion', exact: true }).click()
  await page.getByRole('button', { name: /^Read: / }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(art).toHaveAttribute('data-running', 'false')
  await page.keyboard.press('Escape')
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'true')
})

test('reduced motion applies on load and when the system preference changes', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('./?lang=ur&view=journey&shelf=appearance')
  const art = page.locator('.manuscript-art')
  await art.scrollIntoViewIfNeeded()
  await expect(art).toHaveAttribute('data-running', 'false')
  await expect(page.getByRole('button', { name: 'حرکت محدود ہے', exact: true })).toBeDisabled()
  await expect(art.locator('.rosette-rim')).toHaveCSS('animation-name', 'none')
  await expect(art.locator('.name-calligraphy')).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(art).toHaveAttribute('data-running', 'true')
  await page.getByRole('button', { name: 'حرکت روکیں', exact: true }).click()
  await expect(page.getByRole('button', { name: 'حرکت جاری کریں', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('narrow layouts and enlarged Urdu reading retain accessible content', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('./?lang=ur&view=collection')
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: /^پڑھیے:/ }).first().click()
  await page.getByRole('combobox', { name: 'مطالعے کے متن کا سائز', exact: true }).selectOption('larger')
  const dialog = page.getByRole('dialog')
  await expect(dialog).toHaveCSS('animation-name', 'none')
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await dialog.getByText('مکمل عربی روایت پڑھیں', { exact: true }).click()
  await expect(dialog.locator('[data-full-arabic]')).toBeVisible()
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})
