import { expect, test } from './fixtures.ts'

for (const language of ['en', 'ur'] as const) {
  test(`connected story audio plays, advances and resumes without duplicating the reader (${language})`, async ({ page }) => {
    const requests: string[] = []
    page.on('request', (request) => requests.push(request.url()))
    await page.goto(`./?view=listen&shelf=life&lang=${language}`)
    await expect(page.locator('.narrated-stories')).toBeVisible()
    const audio = page.locator('audio')
    await expect(audio).toHaveCount(1)
    expect(await audio.evaluate((element) => element.paused)).toBe(true)
    await audio.evaluate((element) => { element.muted = true })
    await page.getByRole('button', { name: language === 'en' ? 'Play narrated story' : 'بیانیہ سنیں', exact: true }).click()
    await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(.2)
    await expect(page.locator('.narrated-player')).toBeVisible()
    await expect(page.locator('.listening-player')).not.toBeVisible()
    const first = await audio.getAttribute('src')
    await audio.evaluate((element) => { element.currentTime = element.duration - .12 })
    await expect.poll(() => audio.getAttribute('src')).not.toBe(first)
    await expect(page.locator('.narrated-evidence h2')).toContainText(language === 'en' ? 'first revelation' : 'پہلی وحی')
    await page.locator('.narrated-evidence .story-source-button').first().click()
    const reader = page.getByRole('dialog').filter({ has: page.locator('.reader-body') })
    await expect(reader).toBeVisible()
    await expect(audio).toHaveCount(1)
    await expect(reader.locator('audio')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await expect(reader).not.toBeVisible()
    await page.locator('.narrated-player').getByRole('button', { name: language === 'en' ? 'Pause' : 'روکیں', exact: true }).click()
    await page.reload()
    expect(await audio.evaluate((element) => element.paused)).toBe(true)
    await expect(page.locator('.narrated-evidence h2')).toContainText(language === 'en' ? 'first revelation' : 'پہلی وحی')
    expect(requests.some((url) => /openai\.azure\.com|speech\.microsoft\.com/.test(url))).toBe(false)
    await page.evaluate(() => document.fonts.ready)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('ornamental pointer depth leaves controls stationary and stops with motion paused', async ({ page, isMobile }) => {
  await page.goto('./?view=story&shelf=appearance&topic=complexion&lang=en')
  const stage = page.locator('.story-stage')
  await expect(stage).toHaveAttribute('data-running', 'true')
  await expect(stage.locator('.story-motif-incoming')).toHaveCSS('animation-name', 'manuscript-aperture')
  const before = await stage.locator('select').boundingBox()
  const box = await stage.boundingBox()
  if (!box) throw new Error('Story stage missing')
  await page.mouse.move(box.x + box.width * .7, box.y + box.height * .5)
  await expect(stage).toHaveAttribute('data-pointer-active', isMobile ? 'false' : 'true')
  const after = await stage.locator('select').boundingBox()
  expect(after?.x).toBe(before?.x)
  expect(after?.width).toBe(before?.width)
  await stage.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await expect(stage).toHaveAttribute('data-pointer-active', 'false')
  await expect(page.locator('.story-experience')).toHaveAttribute('data-static', 'true')
})
